### ISSUE TITLE
Rename this package, e.g. to CaratInterface?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/CaratInterface#12]
It's rather easy to get confused between
1. "carat, the standalone tool" and
2.  "carat, the GAP package wrapping the other carat". 

Hmm, well, and I guess 1. also strictly speaking of course is also the name of a whole project, with several binaries...

So perhaps this package could be renamed to reduce the confusion? I would suggest `CaratInterface`. That matches several other such packages, and has the advantage that it has the old package name as a prefix; that means that code using `LoadPackage("carat")` will keep working as before, as that command matches against a package name *prefix*.

There is just one snag that I can think of: the package *dependency* mechanism does not use the prefix approach, it wants an exact match (up to case); so the two packages `cryst` and `hapcryst` would have to be adapted to such a name change. Since @gaehler is maintainer of of both carat and cryst, and since for hapcryst it is less urgent (there, carat is only a suggested, optional dependency), I am fairly confident we could pull this off anyway.

Thoughts?

**Comment by fingolfin** [comment]
Huh, so I just discovered https://github.com/lbfm-rwth/CaratInterface.git by @DominikBernhardt and now I am even more confused about the relative roles of these various packages...

**Comment by gaehler** [comment]
It seems this is a competing GAP interface to Carat by @sebasguts and @DominikBernhardt - maybe we should talk to each other in order not to duplicate too much work. What are the plans with that? Regarding the renaming suggestion, I agree that the naming is a bit confusing: I was distinguishing between Carat (the GAP interface) and CARAT (the binary package), but I'm not sure a renaming is worth the hassle (even more as the good name CaratInterface seems blocked now).

**Comment by DominikBernhardt** [comment]
The repo you discovered @fingolfin was created during a "teaching" sessions @sebasguts gave me for creating kernel extensions. We chose to use Carat for it because I was familiar with the `C` code. I have no time whatsoever to develop this any further. As you might see, the only function we worked on is `Form_space`, I haven't even touched the rest of them. I will make the repo private in order to avoid confusion.

Concerning the renaming: I agree with your suggestion.

**Comment by gaehler** [comment]
I'm not opposed to renaming, but I have some questions. Renaming can be done in three steps:
1. Change the name of the package to CaratInterface. This essentially requires some changes in the documentation, but is not difficult, nor much work.
2. Change the directory in which the package is installed. Not difficult either.
3. Change the directory in which the package is hosted on GitHub

I have no idea how 3 is best done. Doing 1 and 2, but not 3, or even only 1, might be confusing. If this renaming is done, it should be either done soon, or postponed until after the next release. Any thoughts, @fingolfin, @alex-konovalov ?

**Comment by fingolfin** [comment]
From my POV there is no reason why this couldn't be done right now, before the next release; but since that is imminent, it's best to wait for @alex-konovalov's word on this; after all, it doesn't hurt to delay the renaming a bit more.

Doing step 3 involves going to <https://github.com/gap-packages/carat/settings>; there at the top you can rename the repository. Redirects from https://github.com/gap-packages/carat to https://github.com/gap-packages/CaratInterface are automatically provided, too.

I would strongly recommend doing all of 1+2+3.

**Comment by alex-konovalov** [comment]
No objections from me, please go ahead. Let me know when done, I will do the rest of the work in the package update system.

**Comment by gaehler** [comment]
@alex-konovalov I have published new releases of CaratInterface and Cryst (the latter also required some adjustments). The PackageInfo records are still available via the previous locations.

**Comment by alex-konovalov** [comment]
Picked up - testing is underway:
```
* CaratInterface - new version 2.3.1 discovered!!!
  ============================================
  Getting new archives from 
  https://www.math.uni-bielefeld.de/~gaehler/gap/CaratInterface/CaratInterface\
-2.3.1[ ".tar.gz" ]
  unpacking CaratInterface-2.3.1.tar.gz
  Validation of the info file successful!
  Package CaratInterface 2.3.1 from 14/11/2019 has dependencies:
  * GAP >=4.9
  * SuggestedOtherPackages [ [ "Cryst", ">=4.1.17" ] ]
  finding text files  . . .
  using [ "doc/manual.pdf", "doc/manual.dvi", "carat.tgz" 
 ] from PackageInfo.g as binary files 

=====================text files==========================
CaratInterface/README
CaratInterface/init.g
CaratInterface/INSTALL
CaratInterface/read.g
CaratInterface/GPL
CaratInterface/PackageInfo.g
CaratInterface/doc/carat.tex
CaratInterface/doc/introduction.tex
CaratInterface/doc/installation.tex
CaratInterface/doc/manual.tex
CaratInterface/src/setcaratdir.c
CaratInterface/htm/theindex.htm
CaratInterface/htm/CHAP002.htm
CaratInterface/htm/CHAP001.htm
CaratInterface/htm/CHAP003.htm
CaratInterface/htm/chapters.htm
CaratInterface/htm/biblio.htm
CaratInterface/htm/CHAP000.htm
CaratInterface/gap/methods.gi
CaratInterface/gap/carat.gd
CaratInterface/gap/carat.gi
CaratInterface/tst/carat.tst
CaratInterface/tst/testall.g

=====================end of the list of text files=======
=====================binary files========================
CaratInterface/configure
CaratInterface/Makefile
CaratInterface/carat.tgz
CaratInterface/Changelog
CaratInterface/doc/manual.lab
CaratInterface/doc/manual.toc
CaratInterface/doc/make_doc
CaratInterface/doc/manual.mst
CaratInterface/doc/manual.six
CaratInterface/doc/manual.pdf
CaratInterface/doc/manual.bbl

=====================end of the list of binary files=====
=====================ignored files=======================

=====================end of the list of ignored files====
```

**Comment by alex-konovalov** [comment]
This is done - it's now available in package archives used for Travis CI tests under the new name.
