### ISSUE TITLE
Bug in one-dimensional exception for NormalizerInGLnZ

### ISSUE THREAD

**Issue by stertooy** [gap-packages/CaratInterface#24]
This is related to the bug mentioned in 87761049312e1de26fe1cacc759302300ff2bfbf: the following lines were added to make `NormalizerInGLnZ` work if the argument was is one-dimensional integer matrix group:

https://github.com/gap-packages/CaratInterface/blob/58e4b066552294bf18fd279af66be59410ab0b88/gap/methods.gi#L148-L150

The problem is that `GroupByGenerators` takes as input a list of generators. Rather than creating the integer matrix group with generator `[ [ -1 ] ]`, it constructs a 'group' with generator `[ -1 ]`:

```
gap> G := Group( [], IdentityMat(1) );;
gap> gensG := GeneratorsOfGroup( G );
[  ]
gap> One( G );
[ [ 1 ] ]
gap> IsIntegerMatrixGroup( G );
true
gap> N := NormalizerInGLnZ( G );
<group with 1 generators>
gap> gensN := GeneratorsOfGroup( N );
[ [ -1 ] ]
gap> gensN[1];
[ -1 ]
gap> One( N );
1
gap> IsIntegerMatrixGroup( N );
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `IsIntegerMatrixGroup' on 1 arguments at /usr/lib/gap/lib/methsel2.g:249 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at *stdin*:2297
type 'quit;' to quit to outer loop
```
I've submitted PR https://github.com/gap-packages/CaratInterface/pull/23 which should fix this.

**Comment by fingolfin** [comment]
This was fixed in version 2.3.4 via commit c22f0e08dbefde7bce22e1f3957403d63bd7957b
