### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/CaratInterface#31]
The last release of CaratInterface was 2.3.3 from December 2019.

Since then a bunch of changes have accumulated, including a bug fix for NormalizerInGLnZ, and the C source code was removed.

GAP 4.13 is scheduled for mid or late April, and it'd be great to have a new CaratInterface release in it :-)

**Comment by fingolfin** [comment]
@gaehler any chance for this (a new CaratInterface release)?

**Comment by gaehler** [comment]
Sure. I could do that now, but I actually wanted to first merge a pull request in carat which fixes a free after use, but I do not seem to have the power to merge it, and there does not seem to be an active maintainer.

**Comment by fingolfin** [comment]
Can you post a link to the carat PR? Then I'll try to speak to the right people to arrange control

**Comment by gaehler** [comment]
The PR is [here](https://github.com/lbfm-rwth/carat/pull/107). In the meantime, I can also include a patched CARAT in CaratInterface.

**Comment by gaehler** [comment]
Version 3.3.5 is released.
