### ISSUE TITLE
Problems with deleting Carat directory on Windows

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/CaratInterface#5]
See https://github.com/gap-system/gap-distribution/issues/55 reported by @ChrisJefferson. Can we notify the authors of CARAT (i.e. standalone program, see [here](http://wwwb.math.rwth-aachen.de/carat/index.html)) about this? Alternatively, since it is distributed under GPLv3, can we made and document modifications in the version of CARAT included with Carat? 

[Writing this was confusing - some packages decided to append the `Interface` to the name of the package to avoid such confusions. What do you think about renaming it to `CARATInterface`?]

**Comment by gaehler** [comment]
As the README clearly says, this is an interface package to a collection of Unix-only standalones. I see absolutely no reason to unpack the CARAT tarball on Windows. Only then, the problematic files are exposed to Windows.

CARAT is GPLv3 licensed, but its authors seem to have left academia, and it is unclear whether there is any active maintenance. And even if there is, I doubt they will care much about Windows. So far, I have refrained from making changes to the sources of CARAT, or even making a clone. I try to keep it running on Linux, but do not want to become a full maintainer. For that, I do not know the program and its algorithms well enough. And if I would start that, there would be more important things to improve.

**Comment by alex-konovalov** [comment]
I know a temporary workaround (see https://github.com/gap-system/gap-distribution/issues/55) although "there is nothing more permanent than temporary". Also, I think that unpacking the arc hive on Windows at least to study the source code and documentation is a legitimate reason. Also, with Windows 10, it might be that one could even get it running.

**Comment by gaehler** [comment]
The GitHub versions of both CARAT and its GAP interface now have the Windows compatibility patches applied (whether it runs correctly on Windows has yet to be seen). Once there is a new CARAT release, I will update the interface package accordingly.

**Comment by gaehler** [comment]
This should be resolved with release 2.3, although CARAT works on Windows only very partially.

**Comment by gaehler** [comment]
CARAT  should now be ready for Windows, all issues resolved.
