### ISSUE TITLE
configure script looks for files it ought not to rely on

### ISSUE THREAD

**Issue by jengelh** [gap-packages/CaratInterface#6]
The configure script of the current git master (25c01d2c65ad6cd80f076590073ac94152abcaad) appears to be just bogus:
```
[    2s] + ./configure --with-gaproot=/usr/lib64/gap/pkg
[    2s] grep: /usr/lib64/gap/pkg/config.log: No such file or directory
[    2s] which: no wget in (/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin)
[    2s] which: no curl in (/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin)
[    2s] + exit 0
```
1. It must not rely on config.log's presence. That file is not available in a binary distribution.
2. It ought not to rely on a network connection: all extra sources should already be present - or they need to be separately buildable (i.e. another package in terms of a Linux distro).

**Comment by alex-konovalov** [comment]
@jengelh are you sure to call it with `./configure --with-gaproot=/usr/lib64/gap/pkg` and not with `./configure --with-gaproot=/usr/lib64/gap`?

**Comment by fingolfin** [comment]
All of this is resolved in the current version.
